# Test 2025-10-14 at 02:48:41

name: Test
run-name: dockerSiliconCompiler

on:
  push:
    paths:
      - '**/main.yml'

jobs:

  test:
    permissions:
      contents: read
      packages: write  # Needed for GHCR push

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: 'Install silicon compiler in a docker container based on: https://docs.siliconcompiler.com/en/stable/user_guide/installation.html'
      run: |
        cat << 'EOF' > Dockerfile
        FROM ubuntu:22.04

        RUN apt-get update
        RUN apt-get install -y python3-dev python3-pip python3-venv curl git build-essential sudo
        RUN rm -rf /var/lib/apt/lists/*

        # Set working directory
        WORKDIR /app

        # Create virtual environment
        RUN python3 -m venv ./sc

        # Upgrade pip inside virtual environment
        RUN /bin/bash -c "source ./sc/bin/activate && pip install --upgrade pip"

        # Install SiliconCompiler
        RUN /bin/bash -c "source ./sc/bin/activate && pip install siliconcompiler"
        RUN /bin/bash -c "source ./sc/bin/activate && pip show siliconcompiler"
        RUN /bin/bash -c "source ./sc/bin/activate && python3 -c 'import siliconcompiler; print(siliconcompiler.__version__)'"

        # Install ASIC tools via sc-install
        RUN /bin/bash -c "source ./sc/bin/activate && sc-install openroad"
        RUN /bin/bash -c "source ./sc/bin/activate && sc-install klayout"
        RUN /bin/bash -c "source ./sc/bin/activate && sc-install yosys"
        RUN /bin/bash -c "source ./sc/bin/activate && sc-install sv2v"
        RUN /bin/bash -c "source ./sc/bin/activate && sc-install yosys-slang"

        # Default command
        CMD ["/bin/bash"]
        EOF

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/sc-asic:latest .

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/sc-asic:latest
