# Test 2025-10-14 at 01:00:15

name: Test
run-name: dockerSiliconCompiler

on:
  push:
    paths:
      - '**/main.yml'

jobs:

  test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'

    - name: 'Install silicon compiler as described in: https://docs.siliconcompiler.com/en/stable/user_guide/installation.html'
      run: |
        sudo apt update                                                        # Update package information
        sudo apt install python3-dev python3-pip python3-venv                   # Install dependencies
        python3 -m venv  ./sc                                                   # Create a virtual env
        source ./sc/bin/activate                                                # Active virtual env (bash/zsh)
        pip install --upgrade siliconcompiler                                   # Install SiliconCompiler in venv
        pip show siliconcompiler                                                # Display SiliconCompiler package information
        python3 -c "import siliconcompiler;print(siliconcompiler.__version__)"  # Check version

    - name: 'Install tools for ASIC flow as described in: https://docs.siliconcompiler.com/en/latest/reference_manual/apps.html#app-sc-install'
      run: |
        source ./sc/bin/activate                                                # Active virtual env (bash/zsh)
        sc-install openroad
        sc-install klayout
        sc-install yosys
        sc-install -group asic
