# Test 2025-10-15 at 22:56:26

name: Test
run-name: dockerSiliconCompiler

on:
  push:
    paths:
      - '**/run.yml'

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Code to execute in the docker container to place one synthesized module in another
      run: |
        cat <<EOF > exec.sh
        export PATH=/root/.local/bin:$PATH
        source /app/sc/bin/activate
        cd /workspace/verilog
        python3 top.py
        EOF
        chmod +x exec.sh

    - name: Run Silicon compiler in a docker container
      run: |
        docker run --rm -v ".:/workspace/verilog" ghcr.io/philiprbrenan/sc-asic:latest bash -c "bash /workspace/verilog/top.exec"
